### ISSUE TITLE
mod incompatibility

### ISSUE THREAD

**Issue by awawaline** [hkviz/hkviz-mod#6]
incompatibility with the decorationmaster mod, if thats something you care about

**Comment by OliverGrack** [comment]
Fixed it a little, so the mod loads now, but enabling / disabling decorationmaster from the mod settings will being in the main menu, after the game has just started. So enabling after disabling will require a restart of HollowKnight for now. Did try my best to fix that too, but couldnt figure it out for now.

If one just keeps decorationmaster enabled it should work now. 

(For interested devs: decoration master seems to be unable to initialize after I change Fsms using Core.FsmUtil, so I just change the fsm only once a game is started, didn't figure out exactly why that happened until now though).

**Comment by OliverGrack** [comment]
Also thanks @awawaline for telling me about that issue! :)

**Comment by OliverGrack** [comment]
Ahh just saw, the devs of Core.FsmUtil just fixed that issue on their end as well: https://discord.com/channels/879125729936298015/880548951521103962/1197533516225851514
so if you either update both all your mods everything shuld work now.
